
import Header from '@/layout/client/Header'
import '../assets/styles/index.css'
import '../assets/styles/styles.css'
import { Inter } from 'next/font/google'
import Footer from '@/layout/client/Footer'
import { Suspense } from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Suspense fallback={<h1>loading...</h1>}>{children}</Suspense>
        <Footer/>
      </body>
    </html>
  )
}
